SELECT 'FRACTURE' AS CONDITION, COHORT.COHORT_DEFINITION_ID, COHORT.SUBJECT_ID, COHORT.COHORT_START_DATE, CF.CONDITION_CONCEPT_ID, C.CONCEPT_NAME, MIN(CF.CONDITION_START_DATE) AS CONDITION_START_DATE 
FROM  @cohortDatabaseSchema.@cohortTable_DEMOGRAPHICS COHORT
	, (SELECT CO.* FROM @cdmDatabaseSchema.CONDITION_OCCURRENCE CO WHERE CONDITION_CONCEPT_ID IN (SELECT CA.DESCENDANT_CONCEPT_ID FROM @cdmDatabaseSchema.CONCEPT_ANCESTOR CA WHERE ANCESTOR_CONCEPT_ID=75053 AND MIN_LEVELS_OF_SEPARATION>2)) CF
	, @cdmDatabaseSchema.CONCEPT C
WHERE COHORT.SUBJECT_ID = CF.PERSON_ID AND DATEADD(DAY, -365, COHORT.COHORT_START_DATE) <= CONDITION_START_DATE AND COHORT.COHORT_START_DATE>CONDITION_START_DATE
AND C.CONCEPT_ID=CF.CONDITION_CONCEPT_ID
GROUP BY COHORT.COHORT_DEFINITION_ID, COHORT.SUBJECT_ID, COHORT.COHORT_START_DATE, CF.CONDITION_CONCEPT_ID, C.CONCEPT_NAME
UNION ALL 
SELECT 'CKD' AS CONDITION,  COHORT.COHORT_DEFINITION_ID, COHORT.SUBJECT_ID, COHORT.COHORT_START_DATE, CF.CONDITION_CONCEPT_ID, C.CONCEPT_NAME, MIN(CF.CONDITION_START_DATE) AS CONDITION_START_DATE
FROM @cohortDatabaseSchema.@cohortTable_DEMOGRAPHICS COHORT
	,(SELECT CO.* FROM @cdmDatabaseSchema.CONDITION_OCCURRENCE CO WHERE CONDITION_CONCEPT_ID IN (SELECT CA.DESCENDANT_CONCEPT_ID FROM @cdmDatabaseSchema.CONCEPT_ANCESTOR CA WHERE ANCESTOR_CONCEPT_ID=46271022 AND MIN_LEVELS_OF_SEPARATION>2)) CF
	, @cdmDatabaseSchema.CONCEPT C
WHERE COHORT.SUBJECT_ID = CF.PERSON_ID AND DATEADD(DAY, -365, COHORT.COHORT_START_DATE) <= CONDITION_START_DATE AND COHORT.COHORT_START_DATE>CONDITION_START_DATE
AND C.CONCEPT_ID=CF.CONDITION_CONCEPT_ID
GROUP BY COHORT.COHORT_DEFINITION_ID, COHORT.SUBJECT_ID, COHORT.COHORT_START_DATE, CF.CONDITION_CONCEPT_ID, C.CONCEPT_NAME;