SELECT P.PERSON_ID AS SUBJECT_ID
	 , P.GENDER_CONCEPT_ID
	 , CASE WHEN P.GENDER_CONCEPT_ID = 8507 THEN 'MALE'
			WHEN P.GENDER_CONCEPT_ID = 8532 THEN 'FEMALE'
			ELSE 'UNKNOWN' END AS GENDER
	 , CASE WHEN P.DAY_OF_BIRTH = 0 THEN DATEFROMPARTS(P.YEAR_OF_BIRTH, ISNULL(P.MONTH_OF_BIRTH, 7), 15) 
	        ELSE DATEFROMPARTS(P.YEAR_OF_BIRTH, ISNULL(P.MONTH_OF_BIRTH, 7), ISNULL(P.DAY_OF_BIRTH, 15)) END AS DOB
	 , OP.OBSERVATION_PERIOD_START_DATE AS COHORT_START_DATE
	 , OP.OBSERVATION_PERIOD_END_DATE AS COHORT_END_DATE
	 , YEAR(OP.OBSERVATION_PERIOD_START_DATE) AS START_YEAR
	 , YEAR(OP.OBSERVATION_PERIOD_END_DATE) AS END_YEAR
	 , DATEFROMPARTS(YEAR(OP.OBSERVATION_PERIOD_START_DATE)
	 , MONTH(OP.OBSERVATION_PERIOD_START_DATE),1) AS START_YEARMTH
	 , DATEFROMPARTS(YEAR(OP.OBSERVATION_PERIOD_END_DATE)
	 , MONTH(OP.OBSERVATION_PERIOD_END_DATE),1) AS END_YEARMTH
FROM (SELECT * 
	  FROM @cdm_database_schema.PERSON PT
	  JOIN @cohort_database_schema.@cohort_table CT 
	  ON PT.PERSON_ID=CT.SUBJECT_ID
	  WHERE CT.COHORT_DEFINITION_ID IN (2001,2002,2003,2004,2005,2006)) P -- CohortType:DRUG
RIGHT JOIN @cdm_database_schema.OBSERVATION_PERIOD OP ON P.PERSON_ID = OP.PERSON_ID
WHERE YEAR(OP.OBSERVATION_PERIOD_START_DATE) <= @yearStartDate AND YEAR(OP.OBSERVATION_PERIOD_END_DATE) >= @yearEndDate
AND P.YEAR_OF_BIRTH IS NOT NULL
